v5.2

diff --git a/bin/MySB_UpgradeMe b/bin/MySB_UpgradeMe
--- a/bin/MySB_UpgradeMe
+++ b/bin/MySB_UpgradeMe
@@ -32,9 +32,8 @@ Error=""
 #### Updating clock
 echo -e -n "${CBLUE}$UpgradeMe_Clock$CEND..."
 ping -c3 0.fr.pool.ntp.org > /dev/null 2>&1
-if [ $? -gt 0 ]; then
-	gfnSwitchDNS "bind"
-fi
+[ $? -gt 0 ] && gfnSwitchDNS "bind"
+
 /usr/sbin/ntpdate -u 0.fr.pool.ntp.org > /dev/null 2>&1
 if [ $? -eq 0 ]; then
 	echo -e "$Global_Done"
@@ -81,7 +80,8 @@ if [ $Continue -eq 0 ]; then
 	if [ ! -z "$MySB_CurrVersionDiff" ] && [ ! -z "$MySB_NewVersionDiff" ] && [ "$MySB_NewVersionDiff" -gt "$MySB_CurrVersionDiff" ]; then
 		case "$Type" in
 			"CRON")
-				curl -skLS --retry 3 https://raw.githubusercontent.com/toulousain79/MySB/$MySB_NewVersion/Changelog.md -o $MySB_InstallDir/temp/changelog
+				$binCURL https://raw.githubusercontent.com/toulousain79/MySB/$MySB_NewVersion/Changelog.md -o $MySB_InstallDir/temp/changelog
+
 				gfnSendMail "MySB - $UpgradeMe_NewVersion ($MySB_NewVersion)" "$gsMainUserName" "new_version" "$UpgradeMe_NewVersion"
 				[ -f $MySB_InstallDir/temp/changelog ] && rm -f $MySB_InstallDir/temp/changelog
 				gfnEndingScript 0
@@ -93,9 +93,7 @@ if [ $Continue -eq 0 ]; then
 				echo
 				gfnQuestionGetString NO "$Global_WantToContinue" WantToContinue $Global_NO
 				WantToContinue="`echo $WantToContinue | tr '[:lower:]' '[:upper:]'`"
-				if [ "$WantToContinue" == "$Global_NO" ]; then
-					gfnEndingScript 0
-				fi
+				[ "$WantToContinue" == "$Global_NO" ] && gfnEndingScript 0
 			;;
 		esac
 	else
@@ -124,24 +122,14 @@ if [ $Continue -eq 0 ]; then
 		if [ -d /var/lib/mysql/$Database/ ]; then
 			case "$Database" in
 				'mysql'|'performance_schema')	continue;;
-				*)
-					mysqldump --defaults-extra-file=/root/.config.cnf MySB_db --single-transaction $Database > $MySB_InstallDir/db/MySQL_$Database-$DateTime-$gsCurrentVersion.dump.sql
-					if [ $? -ne 0 ]; then
-						Continue=3
-						Error="`echo $UpgradeMe_Error_BackupDatabase | sed "s/#database#/$Database/g;"`"
-					fi
-				;;
+				*)								mysqldump --defaults-extra-file=/root/.config.cnf --single-transaction $Database > $MySB_InstallDir/db/MySQL_$Database-$DateTime-$gsCurrentVersion.dump.sql;;
 			esac
 		fi
-	done
-
-	if [ "$gbIsInstalled_NextCloud" == "YES" ]; then
-		mysqldump --defaults-extra-file=/root/.config.cnf --single-transaction NextCloud_db > $MySB_InstallDir/db/MySQL_NextCloud_db-$DateTime-$gsCurrentVersion.dump.sql
 		if [ $? -ne 0 ]; then
-			Continue=4
-			Error="`echo $UpgradeMe_Error_BackupDatabase | sed "s/#database#/NextCloud_db/g;"`"
+			Continue=3
+			Error="`echo $UpgradeMe_Error_BackupDatabase | sed "s/#database#/$Database/g;"`"
 		fi
-	fi
+	done
 
 	# Creating backup with Backup-Manager
 	[ ! -d ${MySB_InstallDir}_backup/temp ] && mkdir -p ${MySB_InstallDir}_backup/temp
