v99.99

diff --git a/templates/init/etc.init.d.rtorrent.tmpl b/templates/init/etc.init.d.rtorrent.tmpl
--- a/templates/init/etc.init.d.rtorrent.tmpl
+++ b/templates/init/etc.init.d.rtorrent.tmpl
@@ -29,123 +29,113 @@
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
 # Short-Description: Start/stop rtorrent-<username> daemon
+# Description:       Start/stop rtorrent-<username> daemon.
 ### END INIT INFO
 
 PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
 
 #### Includes
-source /etc/MySB/config
-source $MySB_InstallDir/inc/vars
-source /lib/lsb/init-functions
+source /etc/MySB/config || exit 0
+source $MySB_InstallDir/inc/vars || exit 0
+source /lib/lsb/init-functions || exit 0
 
-## Username to run rtorrent under
-Username="<username>"
-if [ -z "`getent passwd $Username`" ]; then
-	echo "User $Username does not exist !"
-	exit 0
-fi
+######################################################################
+#
+# S T A R T   C U S T O M I Z A T I O N S
+#
+######################################################################
 
-## User home dir
-HomeDir="/home/$Username"
+#------------------------------------------------------------
+# rTorrent Infos
+#------------------------------------------------------------
+gsUsername="<username>" # Username to run rtorrent under
+gsHomeDir="/home/$gsUsername" # User home dir
+gsSessionDir="$gsHomeDir/rtorrent/.session" # rTorrent session directory
+gsPidFile="/var/run/rtorrent-$gsUsername.pid" # PID file
+gsLockFile="$gsSessionDir/rtorrent.lock" # Lock file
+gsBinName="rtorrent-$gsUsername"
+gsBinDesc="rTorrent for $gsUsername"
+#------------------------------------------------------------
+# Binary
+#------------------------------------------------------------
+binRtorrent="/usr/bin/rtorrent" # rTorrent bin
+binScreen="/usr/bin/screen" # Screen binary
+#------------------------------------------------------------
+# Log
+#------------------------------------------------------------
+gsLogFile="$gsHomeDir/logs/rTorrentInit.log"
 
-## Absolute path to the rtorrent binary.
-rTorrentVersion="`cmdMySQL 'MySB_db' "SELECT rtorrent_version FROM users WHERE users_ident='$Username';"`"
-case "$rTorrentVersion" in
-	"v0.9.6")	rTorrentBin="/usr/bin/rtorrent";;
-	*)			rTorrentBin="/usr/bin/rtorrent";;
-esac
+######################################################################
+#
+# E N D   C U S T O M I Z A T I O N S
+#
+######################################################################
 
-## Absolute path to the screen binary.
-ScreenBin="/usr/bin/screen"
+######################################################################
+#
+# S T A R T   W O R K S P A C E
+#
+######################################################################
 
-## the full path to the filename where you store your rtorrent configuration
-ConfigFile="$HomeDir/.rtorrent.rc"
-
-## rTorrent session directory
-SessionDir="`cat $ConfigFile | grep "^[[:space:]]*session.path.set[[:space:]]*=" | sed "s/^[[:space:]]*session.path.set[[:space:]]*=[[:space:]]*//"`"
-
-## Command Infos
-CommandName="rtorrent-$Username"
-CommandDescription="rTorrent for $Username"
-
-## Absolute path to rtorrent's PID file.
-PidFile="/var/run/rtorrent-$Username.pid"
-
-## LOG
-LogFile="$HomeDir/logs/rTorrentInit.log"
-if ! [ -e $LogFile ]; then
-	touch $LogFile
-fi
-
-## Sync DB
-if [ ! -f $HomeDir/db/$Username.sq3 ]; then
-	cp $gsSync_DB $HomeDir/db/$Username.sq3
-	chmod -R 0770 $HomeDir/db
-	chown -R $FnUser:www-data $HomeDir/db
-fi
+#------------------------------------------------------------
+# Functions - Begin
+#------------------------------------------------------------
 
 ## Create PID file for rTorrent
-CreatePidFile() {
-	sleep 2
-	if [ -e $SessionDir/rtorrent.lock ]; then
-		cat $SessionDir/rtorrent.lock | awk -F: '{print($2)}' | sed "s/[^0-9]//g" > $SessionDir/rtorrent.pid
-		echo "Create rTorrent PID file: "`/bin/date '+%Y-%m-%d - %H:%M:%S'` >> $LogFile
+gfnCreatePidFile() {
+	sleep 1
+	if [ -e $gsLockFile ]; then
+		cat $gsLockFile | awk -F: '{print($2)}' | sed "s/[^0-9]//g" > $gsPidFile
+		echo "Create rTorrent PID file: "`/bin/date '+%Y-%m-%d - %H:%M:%S'` >> $gsLogFile
 	fi
 }
 
-## Delete rtorrent.lock
-DeleteLockFile() {
-    if [ -e $SessionDir/rtorrent.lock ]; then
-        rm -vf $SessionDir/rtorrent.lock >> $LogFile
-		echo "Delete rTorrent LOCK file: "`/bin/date '+%Y-%m-%d - %H:%M:%S'` >> $LogFile
-    fi
-    if [ -e $SessionDir/rtorrent.pid ]; then
-        rm -vf $SessionDir/rtorrent.pid >> $LogFile
-		echo "Delete rTorrent PID file: "`/bin/date '+%Y-%m-%d - %H:%M:%S'` >> $LogFile
-    fi
-}
-
-## Delete user PID file
-DeletePidFile() {
-    if [ -e $PidFile ]; then
-        rm -vf $PidFile >> $LogFile
-		echo "Delete screen PID file: "`/bin/date '+%Y-%m-%d - %H:%M:%S'` >> $LogFile
-    fi
+## Delete PID file and rtorrent.lock
+gfnDeletePidLockFile() {
+	if [ -e $gsPidFile ]; then
+		pidofproc -p $gsPidFile $binScreen &> /dev/null || rm -f $gsPidFile $gsLockFile 2>> $gsLogFile
+	fi
+    rm -vf $gsLockFile >> $gsLogFile
+    echo "Delete rTorrent LOCK file: "`/bin/date '+%Y-%m-%d - %H:%M:%S'` >> $gsLogFile
+    rm -vf $gsPidFile >> $gsLogFile
+    echo "Delete rTorrent PID file: "`/bin/date '+%Y-%m-%d - %H:%M:%S'` >> $gsLogFile
 }
 
 ## mount share dir for seedbox users
-MountShareDir() {
-	MOUNT="`mount -l 2> /dev/null | grep "$HomeDir/rtorrent/share"`"
+gfnMountShareDir() {
+    local sMountList
+	sMountList="`mount -l 2> /dev/null | grep "$gsHomeDir/rtorrent/share"`"
 
 	case "$1" in
-		"mount")
-			if [ -z "$MOUNT" ]; then
-				umount $HomeDir/rtorrent/share > /dev/null 2>&1
-				mount --bind /home/MySB_share $HomeDir/rtorrent/share 2>> $LogFile
+		'mount')
+			if [ -z "$sMountList" ]; then
+				umount $gsHomeDir/rtorrent/share > /dev/null 2>&1
+				mount --bind /home/MySB_share $gsHomeDir/rtorrent/share 2>> $gsLogFile
 			fi
 		;;
-		"umount")
-			if [ ! -z "$MOUNT" ]; then
-				umount $HomeDir/rtorrent/share 2>> $LogFile
+		'umount')
+			if [ ! -z "$sMountList" ]; then
+				umount $gsHomeDir/rtorrent/share 2>> $gsLogFile
 			fi
 		;;
 	esac
 }
 
 ## mount torrents dir for seedbox users
-MountTorrentsDir() {
-	MOUNT="`mount -l 2> /dev/null | grep "$HomeDir/rtorrent/torrents"`"
+gfnMountTorrentsDir() {
+    local sMountList
+	sMountList="`mount -l 2> /dev/null | grep "$gsHomeDir/rtorrent/torrents"`"
 
 	case "$1" in
-		"mount")
-			if [ -z "$MOUNT" ] && [ -d $gsRutorrentDir/share/users/$Username/torrents ]; then
-				umount $HomeDir/rtorrent/torrents > /dev/null 2>&1
-				mount --bind $gsRutorrentDir/share/users/$Username/torrents $HomeDir/rtorrent/torrents 2>> $LogFile
+		'mount')
+			if [ -z "$sMountList" ] && [ -d $gsRutorrentDir/share/users/$gsUsername/torrents ]; then
+				umount $gsHomeDir/rtorrent/torrents > /dev/null 2>&1
+				mount --bind $gsRutorrentDir/share/users/$gsUsername/torrents $gsHomeDir/rtorrent/torrents 2>> $gsLogFile
 			fi
 		;;
-		"umount")
-			if [ ! -z "$MOUNT" ]; then
-				umount $HomeDir/rtorrent/torrents 2>> $LogFile
+		'umount')
+			if [ ! -z "$sMountList" ]; then
+				umount $gsHomeDir/rtorrent/torrents 2>> $gsLogFile
 			fi
 		;;
 	esac
@@ -154,188 +144,210 @@ MountTorrentsDir() {
 #
 # Function that starts the daemon/service
 #
-DoStart() {
-	MountShareDir 'mount'
-	MountTorrentsDir 'mount'
+gfnDoStart() {
+    # Mount
+	gfnMountShareDir 'mount'
+	gfnMountTorrentsDir 'mount'
+
+    # Create config file
 	source $MySB_InstallDir/inc/funcs_by_script/funcs_MySB_CreateUser
-	gfnCreateRtorrentConfigFile "$Username"
+	gfnCreateRtorrentConfigFile "$gsUsername"
 
-	# Delete ghost screen pid file
-	if [ -e $PidFile ]; then
-		pidofproc -p $PidFile $ScreenBin &> /dev/null || rm -f $PidFile
-	fi
-
-	# Delete ghost rtorrent lock file
-	if [ -e $SessionDir/rtorrent.pid ]; then
-		pidofproc -p $SessionDir/rtorrent.pid $ScreenBin &> /dev/null || rm -f $SessionDir/rtorrent.pid $SessionDir/rtorrent.lock 2>> $LogFile
-	fi
+	# Delete ghost pid and lock file
+	gfnDeletePidLockFile
 
 	# Return
 	#   0 if daemon has been started
 	#   1 if daemon was already running
 	#   2 if daemon could not be started
 	start-stop-daemon --start --quiet --background --make-pidfile --test \
-		--pidfile $PidFile\
-		--chuid $Username\
-		--exec $ScreenBin\
-		-- -DmUS $CommandName $rTorrentBin\
-		 2>> $LogFile || return 1
+		--pidfile $gsPidFile\
+		--chuid $gsUsername\
+		--exec $binScreen\
+		-- -DmUS $gsBinName $binRtorrent\
+		 2>> $gsLogFile || return 1
 
 	start-stop-daemon --start --quiet --background --make-pidfile \
-		--pidfile $PidFile\
-		--chuid $Username\
-		--exec $ScreenBin\
-		-- -DmUS $CommandName $rTorrentBin\
-		 2>> $LogFile || return 2
+		--pidfile $gsPidFile\
+		--chuid $gsUsername\
+		--exec $binScreen\
+		-- -DmUS $gsBinName $binRtorrent\
+		 2>> $gsLogFile || return 2
 }
 
 #
 # Function that stops the daemon/service
 #
-DoStop() {
-	MountShareDir 'umount'
-	MountTorrentsDir 'umount'
+gfnDoStop() {
+    local nReturn sGhostProcess
+
+    # Unmout
+	gfnMountShareDir 'umount'
+	gfnMountTorrentsDir 'umount'
 
 	# Return
 	#   0 if daemon has been stopped
 	#   1 if daemon was already stopped
 	#   2 if daemon could not be stopped
 	#   other if a failure occurred
-	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PidFile --exec "$ScreenBin" 2>> $LogFile
-	RETVAL="$?"
+	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $gsPidFile --exec $binScreen 2>> $gsLogFile
+	nReturn="$?"
 
-	sleep 1
+    sGhostProcess="`ps ax | grep "rtorrent-$gsUsername $binRtorrent" | grep -v 'grep' | awk '{ print $1 }'`"
+    [ ! -z "$sGhostProcess" ] && kill -9 $sGhostProcess
+    gfnDeletePidLockFile
 
-	case "$RETVAL" in
-		0|1)
-			DeleteLockFile
-			DeletePidFile
-		;;
-		2)
-			GhostProcess="`ps ax | grep "rtorrent-$Username" | grep -v 'grep' | awk '{ print $1 }'`"
-			if [ ! -z "$GhostProcess" ]; then
-				kill -9 $GhostProcess
-			fi
-			DeleteLockFile
-			DeletePidFile
-		;;
-	esac
-
-	return "$RETVAL"
+	return "$nReturn"
 }
 
 #
 # Function that sends a SIGHUP to the daemon/service
 #
-DoReload() {
-	echo "RELOAD: "`/bin/date '+%Y-%m-%d - %H:%M:%S'` >> $LogFile
+gfnDoReload() {
+	echo "RELOAD: "`/bin/date '+%Y-%m-%d - %H:%M:%S'` >> $gsLogFile
 	# Delete ghost screen pid file
-	if [ -e $PidFile ]; then
-		pidofproc -p $PidFile $ScreenBin &> /dev/null || rm -f $PidFile
+	if [ -e $gsPidFile ]; then
+		pidofproc -p $gsPidFile $binScreen &> /dev/null || rm -f $gsPidFile
 	fi
 
 	# Delete ghost rtorrent lock file
-	if [ -e $SessionDir/rtorrent.pid ]; then
-		pidofproc -p $SessionDir/rtorrent.pid $ScreenBin &> /dev/null || rm -f $SessionDir/rtorrent.pid $SessionDir/rtorrent.lock 2>> $LogFile
+	if [ -e $gsPidFile ]; then
+		pidofproc -p $gsPidFile $binScreen &> /dev/null || rm -f $gsPidFile $gsLockFile 2>> $gsLogFile
 	fi
 
-	start-stop-daemon --stop --signal HUP --quiet --pidfile $PidFile --exec "$ScreenBin" 2>> $LogFile
+	start-stop-daemon --stop --signal HUP --quiet --pidfile $gsPidFile --exec $binScreen 2>> $gsLogFile
 	return $?
 }
 
 #
 # Function stop case
 #
-RestartStopCase() {
-	DoStart
+gfnRestartStopCase() {
+	gfnDoStart
 	case "$?" in
 		0)
-			echo "RESTART: "`/bin/date '+%Y-%m-%d - %H:%M:%S'` >> $LogFile
-			CreatePidFile
-			cmdMySQL 'MySB_db' "UPDATE users SET rtorrent_restart='0' WHERE users_ident='$Username';"
+			echo "RESTART: "`/bin/date '+%Y-%m-%d - %H:%M:%S'` >> $gsLogFile
+			gfnCreatePidFile
+			cmdMySQL 'MySB_db' "UPDATE users SET rtorrent_restart='0' WHERE users_ident='$gsUsername';"
 			log_end_msg 0
 		;;
 		1) # Old process is still running
-			echo "Could not be restarted, old process is still running: "`/bin/date '+%Y-%m-%d - %H:%M:%S'` >> $LogFile
-			CreatePidFile
+			echo "Could not be restarted, old process is still running: "`/bin/date '+%Y-%m-%d - %H:%M:%S'` >> $gsLogFile
+			gfnCreatePidFile
 			log_end_msg 1
 		;;
 		*) # Failed to start
-			echo "Could not be restarted: "`/bin/date '+%Y-%m-%d - %H:%M:%S'` >> $LogFile
-			DeleteLockFile
-			DeletePidFile
+			echo "Could not be restarted: "`/bin/date '+%Y-%m-%d - %H:%M:%S'` >> $gsLogFile
+			gfnDeletePidLockFile
 			log_end_msg 1
 		;;
 	esac
 }
 
+#------------------------------------------------------------
+# Functions - End
+#------------------------------------------------------------
+
+######################################################################
+#
+# E N D   W O R K S P A C E
+#
+######################################################################
+
+######################################################################
+#
+# S T A R T   C O M M A N D   L I N E   M O D E
+#
+######################################################################
+
+## Check if user exist
+if [ -z "`getent passwd $gsUsername`" ]; then
+	echo "User $gsUsername does not exist !"
+	exit 0
+fi
+
+## Create log file
+if ! [ -e $gsLogFile ]; then
+	touch $gsLogFile
+fi
+
+## Sync DB
+if [ ! -f $gsHomeDir/db/$gsUsername.sq3 ]; then
+	cp $gsSync_DB $gsHomeDir/db/$gsUsername.sq3
+	chmod -R 0770 $gsHomeDir/db
+	chown -R $FnUser:www-data $gsHomeDir/db
+fi
+
+## Options
 case "$1" in
-	start)
-		log_daemon_msg "Starting $CommandDescription" "$CommandName"
-		DoStart
+	'start')
+		log_daemon_msg "Starting $gsBinDesc" "$gsBinName"
+		gfnDoStart
 		case "$?" in
 			0)
-				echo "START: "`/bin/date '+%Y-%m-%d - %H:%M:%S'` >> $LogFile
-				CreatePidFile
-				cmdMySQL 'MySB_db' "UPDATE users SET rtorrent_restart='0' WHERE users_ident='$Username';"
+				echo "START: "`/bin/date '+%Y-%m-%d - %H:%M:%S'` >> $gsLogFile
+				gfnCreatePidFile
+				cmdMySQL 'MySB_db' "UPDATE users SET rtorrent_restart='0' WHERE users_ident='$gsUsername';"
 				log_end_msg 0
 			;;
 			1)
-				echo "Already running: "`/bin/date '+%Y-%m-%d - %H:%M:%S'` >> $LogFile
-				CreatePidFile
+				echo "Already running: "`/bin/date '+%Y-%m-%d - %H:%M:%S'` >> $gsLogFile
+				gfnCreatePidFile
 				log_end_msg 0
 			;;
 			2)
-				echo "Could not be started: "`/bin/date '+%Y-%m-%d - %H:%M:%S'` >> $LogFile
-				DeleteLockFile
-				DeletePidFile
+				echo "Could not be started: "`/bin/date '+%Y-%m-%d - %H:%M:%S'` >> $gsLogFile
+				gfnDeletePidLockFile
 				log_end_msg 1
 			;;
 		esac
 	;;
-
-	stop)
-		log_daemon_msg "Stopping $CommandDescription" "$CommandName"
-		DoStop
+	'stop')
+		log_daemon_msg "Stopping $gsBinDesc" "$gsBinName"
+		gfnDoStop
 		case "$?" in
 			0)
-				echo "STOP: "`/bin/date '+%Y-%m-%d - %H:%M:%S'` >> $LogFile
+				echo "STOP: "`/bin/date '+%Y-%m-%d - %H:%M:%S'` >> $gsLogFile
 				log_end_msg 0
 			;;
 			1)
-				echo "Already stopped: "`/bin/date '+%Y-%m-%d - %H:%M:%S'` >> $LogFile
+				echo "Already stopped: "`/bin/date '+%Y-%m-%d - %H:%M:%S'` >> $gsLogFile
 				log_end_msg 0
 			;;
 			2)
-				echo "Could not be stopped, the process was killed: "`/bin/date '+%Y-%m-%d - %H:%M:%S'` >> $LogFile
+				echo "Could not be stopped, the process was killed: "`/bin/date '+%Y-%m-%d - %H:%M:%S'` >> $gsLogFile
 				log_end_msg 1
 			;;
 		esac
 	;;
-
-	restart)
-		log_daemon_msg "Restarting $CommandDescription" "$CommandName"
-		DoStop
+	'restart')
+		log_daemon_msg "Restarting $gsBinDesc" "$gsBinName"
+		gfnDoStop
 		case "$?" in
-			0)	RestartStopCase;;
-			1)	RestartStopCase;;
+			0)	gfnRestartStopCase;;
+			1)	gfnRestartStopCase;;
 		esac
 	;;
-
-	reload)
-		log_daemon_msg "Reloading $CommandDescription configuration" "$CommandName"
-		DoReload
+	'reload')
+		log_daemon_msg "Reloading $gsBinDesc configuration" "$gsBinName"
+		gfnDoReload
 		log_end_msg $?
 	;;
-
-	status)
-		status_of_proc -p $PidFile "$ScreenBin" "$CommandName" && exit 0 || exit $?
+	'status')
+		status_of_proc -p $gsPidFile "$binScreen" "$gsBinName" && exit 0 || exit $?
 	;;
-
 	*)
-		echo "Usage: service rtorrent-$Username {start|stop|restart|reload|status}"
+		echo "Usage: service rtorrent-$gsUsername {start|stop|restart|reload|status}"
 		exit 3
 	;;
 esac
 
+######################################################################
+#
+# E N D   C O M M A N D   L I N E   M O D E
+#
+######################################################################
+
 exit 0
+
+##################### LAST LINE ######################################
